<?php

class PxlSearchBox_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_search_box';
    protected $title = 'Search Box Pxl';
    protected $icon = 'eicon-search';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_content","label":"Content","tab":"content","controls":[{"name":"pxl_icon","label":"Icon","type":"icons","fa4compatibility":"icon"},{"name":"icon_color","label":"Icon Color","type":"color","selectors":{"{{WRAPPER}} .pxl-search-box .search-submit":"color: {{VALUE}};"}},{"name":"icon_color_hover","label":"Icon Color Hover","type":"color","selectors":{"{{WRAPPER}} .pxl-search-box:hover .search-submit":"color: {{VALUE}};"}},{"name":"bg_icon_color","label":"Background Icon Color","type":"color","selectors":{"{{WRAPPER}} .pxl-search-box .search-submit":"background-color: {{VALUE}};"}},{"name":"icon_font_size","label":"Icon Font Size","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .pxl-search-box .search-submit":"font-size: {{SIZE}}{{UNIT}};"}},{"name":"text_color","label":"Text Color","type":"color","selectors":{"{{WRAPPER}} .pxl-search-box .search-field":"color: {{VALUE}};"}},{"name":"bg_text_color","label":"Background Text Color","type":"color","selectors":{"{{WRAPPER}} .pxl-search-box .search-field":"background-color: {{VALUE}};"}},{"name":"style","label":"Style","type":"select","options":{"style-default":"Default","style-box":"Box"},"default":"style-default"},{"name":"box_color","label":"Box Background Color","type":"color","selectors":{"{{WRAPPER}} .pxl-search-box.style-box .search-field":"background-color: {{VALUE}};"},"condition":{"style":["style-box"]}},{"name":"box_height","label":"Box Height","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .pxl-search-box.style-box .search-field":"height: {{SIZE}}{{UNIT}};"},"condition":{"style":["style-box"]}},{"name":"box_width","label":"Box Width","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .pxl-search-box.style-box":"width: {{SIZE}}{{UNIT}};"},"condition":{"style":["style-box"]}},{"name":"border_type","label":"Border Type","type":"select","options":{"":"None","solid":"Solid","double":"Double","dotted":"Dotted","dashed":"Dashed","groove":"Groove"},"selectors":{"{{WRAPPER}} .pxl-search-box .search-field":"border-style: {{VALUE}} !important;"}},{"name":"border_width","label":"Border Width","type":"dimensions","selectors":{"{{WRAPPER}} .pxl-search-box .search-field":"border-width: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}} !important;"},"responsive":true},{"name":"border_color","label":"Border Color","type":"color","default":"","selectors":{"{{WRAPPER}} .pxl-search-box .search-field":"border-color: {{VALUE}} !important;"}},{"name":"border_radius","label":"Border Radius","type":"dimensions","size_units":["px"],"selectors":{"{{WRAPPER}} .pxl-search-box .search-field":"border-radius: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}