<?php

class PxlSlider_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_slider';
    protected $title = 'Slider Pxl ';
    protected $icon = 'eicon-slider-device';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_content","label":"Content","tab":"content","controls":[{"name":"slide_height","label":"Slider Height","type":"slider","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .pxl-slider--inner":"min-height: {{SIZE}}{{UNIT}};","{{WRAPPER}} .pxl-element-slider .pxl-slider--content, {{WRAPPER}} .pxl-element-slider .pxl-slider--content > .elementor, {{WRAPPER}} .pxl-element-slider .elementor-top-section, {{WRAPPER}} .pxl-element-slider .elementor-top-section > .elementor-container":"height: 100%;"}},{"name":"slides","label":"Slides","type":"repeater","controls":[{"name":"slide_template","label":"Select Template","type":"select","options":["None"],"default":"df","description":"Add new tab template: \"<a href=\"https:\/\/klempner-funke.de\/wp-admin\/edit.php?post_type=pxl-template\" target=\"_blank\">Click Here<\/a>\""},{"name":"bg_color","label":"Background Color","type":"color","selectors":{"{{WRAPPER}} .pxl-element-slider .pxl-slider--inner{{CURRENT_ITEM}}":"background-color: {{VALUE}};"}},{"name":"bg_image","label":"Background Image","type":"media"},{"name":"bg_ken_burns","label":"Background Ken Burns","type":"switcher","default":"false"},{"name":"overlay_color","label":"Overlay Color","type":"color","selectors":{"{{WRAPPER}} .pxl-element-slider .pxl-slider--overlay{{CURRENT_ITEM}}":"background-color: {{VALUE}};"}}]}]},{"name":"section_settings_carousel","label":"Settings","tab":"settings","controls":[{"name":"arrows","label":"Show Arrows","type":"switcher"},{"name":"display_arrow","label":"Hidden Arrows","type":"select","default":"arrows-show","options":{"arrows-show":"Show","arrows-hidden":"Hidden"},"condition":{"arrows":"true"}},{"name":"pagination","label":"Show Pagination","type":"switcher","default":"false"},{"name":"pagination_type","label":"Pagination Type","type":"select","default":"bullets","options":{"bullets":"Bullets","fraction":"Fraction"},"condition":{"pagination":"true"}},{"name":"fraction_color","label":"Fraction Color","type":"color","selectors":{"{{WRAPPER}} .pxl-swiper-sliders .pxl-swiper-dots, {{WRAPPER}} .pxl-swiper-sliders .pxl-swiper-dots span":"color: {{VALUE}};"},"condition":{"pagination_type":"fraction","pagination":"true"}},{"name":"pause_on_hover","label":"Pause on Hover","type":"switcher"},{"name":"autoplay","label":"Autoplay","type":"switcher"},{"name":"autoplay_speed","label":"Autoplay Delay","type":"number","default":5000,"condition":{"autoplay":"true"}},{"name":"infinite","label":"Infinite Loop","type":"switcher"},{"name":"speed","label":"Animation Speed","type":"number","default":500},{"name":"progressbar","label":"Show Progress Bar","type":"switcher","default":"false"}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'swiper','pxl-swiper','fixera-swiper-slider' );
}